Numpy is general purpose array-processing package.Its provides a high performaance multidimensional array object and tools for working with these arrays.

Array is a datastructure which stores the value of same data-type and in python list can store different data type in a list.
Array can only contain same data-type of values.

In [76]:
import numpy as np
my_lst1=[1,2,3,4,5]
type(my_lst1)

list

In [77]:
arr=np.array(my_lst1)
arr

array([1, 2, 3, 4, 5])

In [78]:
arr.shape

(5,)

In [79]:
print(arr)

[1 2 3 4 5]


In [80]:
my_lst2=[6,7,8,9,10]
my_lst3=[11,12,13,14,15]

In [81]:
#Creating a multi dimensional array by using multiple combining lists
array = np.array([my_lst1,my_lst2,my_lst3]) 

In [82]:
#check the shape of an araray
array.shape

(3, 5)

In [83]:
#Reshape the existing array with new dimension
array.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

#Indexing

In [84]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [85]:
arr[4]

5

In [86]:
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [87]:
array[1:3,0:2]

array([[ 6,  7],
       [11, 12]])

In [88]:
array[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [89]:
array[1:3,3:5]

array([[ 9, 10],
       [14, 15]])

In [90]:
#arrange function is used to create an array for an range of number with an step in last 2
np.arange(0,100,3)


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [91]:
a=array.reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [92]:
a[2:3,1:2]

array([[8]])

In [93]:
a[0:2,1:2]

array([[2],
       [5]])

In [94]:
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [95]:
array[2:]=500
array

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [500, 500, 500, 500, 500]])

In [133]:
#Copy Function is to copy the array 
arr1=array.copy()
arr1

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [500, 500, 500, 500, 500]])

In [134]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [135]:
arr1[2:]=1000  #the original array wont be effect if you update the value if you used copy function if u asssign it will effext the original array
arr1

array([[   1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [1000, 1000, 1000, 1000, 1000]])

In [136]:
array

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [500, 500, 500, 500, 500]])

In [137]:
arr1

array([[   1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [1000, 1000, 1000, 1000, 1000]])

In [138]:
val =2
#Conditions in array it is divisible or not
print(arr1 % 2)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [0 0 0 0 0]]


In [139]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [140]:
#random normal distribution betweeen 0 and 1
np.random.randn(3,3)

array([[ 0.40164679, -1.0029372 ,  0.13384466],
       [ 1.1709906 , -1.17920551, -0.1186957 ],
       [ 1.09615058,  0.09516277, -0.87680016]])

In [141]:
#Random numbers btween 0 & 1
np.random.rand(3,3)

array([[0.4623641 , 0.07578969, 0.99398354],
       [0.40718241, 0.67348174, 0.45507032],
       [0.71863965, 0.52926727, 0.40864121]])

In [142]:
#Random numbers in integer
np.random.randint(0,100,8)


array([73, 81,  5, 95,  8, 13, 45, 94])

In [143]:
#the parameters defines the dimensions of an array
np.random.random_sample([3,3])

array([[0.47294221, 0.34760995, 0.29248769],
       [0.37391695, 0.3565177 , 0.69155739],
       [0.5061436 , 0.88511414, 0.40724438]])

In [144]:
print('Thank You')

Thank You
